"""
Custom Tools for ideavalidator
Email sending tool using Gmail API with OAuth 2.0
Web search tool using Tavily API
"""

import base64
import os
import pickle
import re
from datetime import datetime
from email.mime.text import MIMEText
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from tavily import TavilyClient
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


# Gmail API scopes
SCOPES = ['https://www.googleapis.com/auth/gmail.send', 'https://www.googleapis.com/auth/gmail.readonly']


def get_gmail_service():
    """
    Authenticate with Gmail API using OAuth 2.0
    Returns Gmail service object
    """

    credentials = None
    credentials_path = "app/credentials/oauth_credentials.json"
    token_path = "app/credentials/token.json"

    # Load existing token if available
    if os.path.exists(token_path):
        with open(token_path, 'rb') as token_file:
            credentials = pickle.load(token_file)

    # If no valid credentials, get new ones
    if not credentials or not credentials.valid:
        if credentials and credentials.expired and credentials.refresh_token:
            credentials.refresh(Request())
        else:
            # Open browser for user to authorize
            flow = InstalledAppFlow.from_client_secrets_file(
                credentials_path,
                SCOPES
            )
            credentials = flow.run_local_server(port=0)

        # Save token for future use
        with open(token_path, 'wb') as token_file:
            pickle.dump(credentials, token_file)

    # Build and return Gmail service
    service = build('gmail', 'v1', credentials=credentials)
    return service


def format_analysis_as_html(body):
    """Convert plain text analysis to formatted HTML email"""

    # Map section keys to display labels and icons
    sections = [
        ("IDEA SUMMARY",        "💡 Idea Summary"),
        ("PROBLEM STATEMENT",   "🎯 Problem Statement"),
        ("TARGET AUDIENCE",     "👥 Target Audience"),
        ("MARKET VALIDATION",   "📊 Market Validation"),
        ("COMPETITOR ANALYSIS", "🔍 Competitor Analysis"),
        ("MVP RECOMMENDATION",  "🚀 MVP Recommendation"),
        ("RISK ANALYSIS",       "⚠️ Risk Analysis"),
        ("FINAL RECOMMENDATION","✅ Final Recommendation"),
    ]

    # Build HTML sections from the plain text body
    sections_html = ""
    for i, (key, label) in enumerate(sections):
        # Find content between this key and the next one
        next_key = sections[i + 1][0] if i + 1 < len(sections) else None
        if next_key:
            pattern = rf'{re.escape(key)}:\s*(.+?)(?={re.escape(next_key)}:)'
        else:
            pattern = rf'{re.escape(key)}:\s*(.+?)$'

        match = re.search(pattern, body, re.DOTALL)
        content = match.group(1).strip() if match else ""

        # Convert newlines to <br> for HTML
        content_html = content.replace('\n', '<br>')

        sections_html += f"""
        <div class="section">
            <h2>{label}</h2>
            <p>{content_html}</p>
        </div>
        <hr>
        """

    html_template = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.7; color: #333; background: #f4f4f4; margin: 0; padding: 20px; }}
            .container {{ max-width: 700px; margin: 0 auto; background: #fff; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); overflow: hidden; }}
            .header {{ background: linear-gradient(135deg, #667eea, #764ba2); color: white; padding: 30px 20px; text-align: center; }}
            .header h1 {{ margin: 0; font-size: 26px; }}
            .content {{ padding: 30px 25px; }}
            .section {{ margin: 20px 0; }}
            h2 {{ color: #667eea; font-size: 17px; border-bottom: 2px solid #667eea; padding-bottom: 6px; margin-bottom: 10px; }}
            p {{ margin: 0; font-size: 15px; }}
            hr {{ border: none; border-top: 1px solid #eee; margin: 20px 0; }}
            .footer {{ background: #f9f9f9; padding: 15px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #ddd; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>📊 Project Analysis Results</h1>
                <p>Your AI-powered project validation report</p>
            </div>
            <div class="content">
                {sections_html}
            </div>
            <div class="footer">
                Generated by AI Project Idea Validator | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            </div>
        </div>
    </body>
    </html>
    """
    return html_template


def send_email_to_user(email_address, subject, body):
    """
    Send project analysis results to user's email using Gmail API with OAuth 2.0

    Parameters:
    -----------
    email_address : str
        Recipient email address
    subject : str
        Email subject line
    body : str
        Email body content (analysis results)

    Returns:
    --------
    str
        Confirmation message
    """

    try:
        # Check if credentials file exists
        credentials_path = "app/credentials/oauth_credentials.json"

        if not os.path.exists(credentials_path):
            return f"❌ Error: OAuth credentials file not found at {credentials_path}"

        # Get Gmail service (with OAuth 2.0 authentication)
        service = get_gmail_service()

        # Convert analysis to HTML format
        html_body = format_analysis_as_html(body)

        # Create email message with HTML content
        message = MIMEText(html_body, 'html')
        message['to'] = email_address
        message['subject'] = subject

        # Encode message in base64
        raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode()

        # Send the email
        send_message = {'raw': raw_message}
        result = service.users().messages().send(
            userId='me',
            body=send_message
        ).execute()

        # Get sender email
        profile = service.users().getProfile(userId='me').execute()
        sender_email = profile.get('emailAddress', 'your-email@gmail.com')

        # Return success message
        confirmation = f"""✅ Email sent successfully!

To: {email_address}
From: {sender_email}
Subject: {subject}
Message ID: {result.get('id')}"""

        return confirmation

    except HttpError as error:
        return f"❌ Gmail API Error: {error}"
    except FileNotFoundError:
        return f"❌ Error: Credentials file not found"
    except Exception as error:
        return f"❌ Error sending email: {str(error)}"


def tavily_search(query):
    """
    Search the web using Tavily API for real-time information

    Parameters:
    -----------
    query : str
        Search query (e.g., "AI market size 2026")

    Returns:
    --------
    str
        Search results formatted as readable text
    """

    try:
        # Get API key from environment variable
        api_key = os.getenv("TAVILY_API_KEY")

        if not api_key:
            return "❌ Error: TAVILY_API_KEY not found in .env file"

        # Initialize Tavily client
        client = TavilyClient(api_key=api_key)

        # Search the web
        response = client.search(
            query=query,
            max_results=5,  # Return top 5 results
            include_answer=True
        )

        # Format results
        if response.get("answer"):
            search_results = f"""Search Results for: "{query}"

            Answer: {response['answer']}

            Sources:
            """
            
            for i, result in enumerate(response.get("results", []), 1):
                search_results += f"\n{i}. {result['title']}\n   URL: {result['url']}\n   {result['content'][:150]}...\n"

            return search_results

        else:
            return f"❌ No results found for: {query}"

    except Exception as error:
        return f"❌ Error searching web: {str(error)}"
